
include ../../common/Makefile.defs

RM := rm.exe -rf


TOOL_PATH_ROOT = ../../../../tools
CLI_TOOL = $(TOOL_PATH_ROOT)/../workspace/tools/push-app.ps1
MKDIR := C:/Program Files/Git/usr/bin/mkdir.exe
FIND := C:/Program Files/Git/usr/bin/find.exe


TARGET_NAME = quectel_demo_gpio
BUILDDIR = out
MODULE = bg96


export CLI_TOOL TARGET_NAME BUILDDIR

include ../../../tools/Makefile.tools